### ISSUE TITLE
Bug: Non-terminating decimal expansion

### ISSUE THREAD

**Issue by ottlinger** [ottlinger/game-kaiser-java#1]
Wieviel Land wollen Sie bebauen?
100

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1780)
	at de.aikiit.game.kaiser.KaiserEngine.finishRoundAfterActions(KaiserEngine.java:199)
	at de.aikiit.game.kaiser.KaiserGame.run(KaiserGame.java:27)
	at de.aikiit.game.kaiser.GameKaiserJavaApplication.main(GameKaiserJavaApplication.java:8)
	... 7 more

**Comment by ottlinger** [comment]
Solution: add scale parameter to any divisions!
But this changes the whole program logics

**Comment by ottlinger** [comment]
Cope with the mix of different scales via rounding:
https://stackoverflow.com/questions/4134047/java-bigdecimal-round-to-the-nearest-whole-value

```
public static BigDecimal roundBigDecimal(final BigDecimal input){
    return input.round(
        new MathContext(
            input.toBigInteger().toString().length(),
            RoundingMode.HALF_UP
        )
    );
}
```

vs.
`bdValue.setScale(0, BigDecimal.ROUND_HALF_UP);`

**Comment by ottlinger** [comment]
Set scale to 0 in all division operations.
